# Generated by Django 3.0.8 on 2020-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkapp', '0004_auto_20200823_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
